### ISSUE TITLE
preupgrade failed on DNF requirement

### ISSUE THREAD

**Issue by Cloud86SysOP** [plesk/cloudlinux7to8#38] opened 2024-10-09 20:13 UTC
**Describe the bug**
In the preupgrade the conversion failed on dependency during the Imunify360 installation. 

```
2024-10-09 21:37:00,491 - ERROR - Command ['/usr/bin/leapp', 'preupgrade'] failed with return code 1
2024-10-09 21:37:00,492 - ERROR - Failed: doing the conversion. The reason: Command '['/usr/bin/leapp', 'preupgrade']' returned non-zero exit status 1.
2024-10-09 21:37:00,620 - DEBUG - Going to write json '/usr/local/psa/var/cloudlinux7to8/actions.json' with new data
2024-10-09 21:37:00,625 - DEBUG - Error report: [cloudlinux7to8] (dist-upgrader 8a71a4b240bcb06c170e11261da0893691db3dd6, upgrader module Plesk::CloudLinux7to8Upgrader 09cd157eb03577666e2a0bbe9b784615de8cebf9) process has failed. Error: 
Failed: doing the conversion. The reason: Command '['/usr/bin/leapp', 'preupgrade']' returned non-zero exit status 1.

2024-10-09 21:37:00,276 - INFO - - package imunify360-webshield-bundle-1.11-2.el8.x86_64 from alma-imunify360-testing requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,276 - INFO - - package imunify360-webshield-bundle-1.11-1.el8.x86_64 from alma-imunify360-testing requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,276 - INFO - - package imunify360-webshield-bundle-1.30.0-2.el8.x86_64 from alma-imunify360-rollout-1-bypass requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,276 - INFO - - package imunify360-webshield-bundle-1.28.2-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,276 - INFO - - package imunify360-webshield-bundle-1.28.0-2.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,276 - INFO - - package imunify360-webshield-bundle-1.27.2-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,276 - INFO - - package imunify360-webshield-bundle-1.27.1-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,276 - INFO - - package imunify360-webshield-bundle-1.26.2-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,276 - INFO - - package imunify360-webshield-bundle-1.25.5-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,276 - INFO - - package imunify360-webshield-bundle-1.25.4-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,276 - INFO - - package imunify360-webshield-bundle-1.25.3-2.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.25.2-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.25.1-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.25.0-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.23.7-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.23.6-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.23.5-2.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.23.4-2.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.23.3-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.23.2-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.23.1-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.22.2-2.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.22.1-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.22.0-2.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.20.124-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.20.121-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.20.120-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.20.119-17.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.20.119-16.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,277 - INFO - - package imunify360-webshield-bundle-1.20.119-14.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.20.119-13.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.19-6.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.19-3.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.19-10.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.18-7.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.18-6.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.18-5.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.18-4.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.18-11.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.17-5.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.17-4.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.16-7.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.16-4.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.15-8.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.14-18.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.14-15.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.13-3.8.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,278 - INFO - - package imunify360-webshield-bundle-1.13-3.4.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,279 - INFO - - package imunify360-webshield-bundle-1.13-3.3.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,279 - INFO - - package imunify360-webshield-bundle-1.13-3.11.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,279 - INFO - - package imunify360-webshield-bundle-1.13-2.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,279 - INFO - - package imunify360-webshield-bundle-1.12-8.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,279 - INFO - - package imunify360-webshield-bundle-1.12-5.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,461 - INFO - - package imunify360-webshield-bundle-1.12-5.1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,461 - INFO - - package imunify360-webshield-bundle-1.12-15.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,461 - INFO - - package imunify360-webshield-bundle-1.12-12.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,461 - INFO - - package imunify360-webshield-bundle-1.11-4.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,461 - INFO - - package imunify360-webshield-bundle-1.11-2.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,461 - INFO - - package imunify360-webshield-bundle-1.11-1.el8.x86_64 from cloudlinux8-imunify360 requires alt-curl, but none of the providers can be installed
2024-10-09 21:37:00,461 - INFO - - package alt-curl-7.64.0-2.el8.x86_64 from cloudlinux-x86_64-server-8 requires alt-libcurl = 7.64.0-2.el8, but none of the providers can be installed
2024-10-09 21:37:00,462 - INFO - - package alt-curl-7.64.0-2.el8.x86_64 from cloudlinux8-imunify360 requires alt-libcurl = 7.64.0-2.el8, but none of the providers can be installed
2024-10-09 21:37:00,462 - INFO - - package alt-curl-7.64.0-2.el8.x86_64 from cloudlinux8-appstream requires alt-libcurl = 7.64.0-2.el8, but none of the providers can be installed
2024-10-09 21:37:00,462 - INFO - - package alt-curl-7.64.0-2.el8.x86_64 from alma-imunify360 requires alt-libcurl = 7.64.0-2.el8, but none of the providers can be installed
2024-10-09 21:37:00,462 - INFO - - package alt-libcurl-7.64.0-2.el8.x86_64 from cloudlinux-x86_64-server-8 requires libssh2(x86-64), but none of the providers can be installed
2024-10-09 21:37:00,462 - INFO - - package alt-libcurl-7.64.0-2.el8.x86_64 from cloudlinux8-imunify360 requires libssh2(x86-64), but none of the providers can be installed
2024-10-09 21:37:00,462 - INFO - - package alt-libcurl-7.64.0-2.el8.x86_64 from cloudlinux8-appstream requires libssh2(x86-64), but none of the providers can be installed
2024-10-09 21:37:00,462 - INFO - - package alt-libcurl-7.64.0-2.el8.x86_64 from alma-imunify360 requires libssh2(x86-64), but none of the providers can be installed
2024-10-09 21:37:00,462 - INFO - - imunify360-webshield-bundle-1.28.2-1.el7.x86_64 from @System  does not belong to a distupgrade repository
2024-10-09 21:37:00,462 - INFO - - alt-curl-7.64.0-1.el7.x86_64 from @System  does not belong to a distupgrade repository
2024-10-09 21:37:00,462 - INFO - - conflicting requests
```

**Feedback archive**
*Please attach a feedback archive to the bug report.*

[cloudlinux7to8_feedback.zip](https://github.com/user-attachments/files/17318134/cloudlinux7to8_feedback.zip)

**Comment by Cloud86SysOP** [comment] 2024-10-29 10:07
Update from our side; Issue is still there with the newest update off the CloudLinux 7 to 8 tool (1.0.3).

![image](https://github.com/user-attachments/assets/f6e75bec-cd35-449f-8ca5-f12b6b64775e)

**Comment by MrKoopie** [comment] 2024-11-06 15:45
Created a case with Plesk support (id 95395954), hopefully this helps with fixing this issue since the developer seems to ignore this.

**Comment by vizovitin** [comment] 2024-11-07 12:23
PAUX-6547

**Comment by vizovitin** [comment] 2024-11-07 16:03
Alternatively, as a rather crude, but straightforward workaround, you can try to do: `yum remove imunify360-webshield-bundle`.

**Comment by MrKoopie** [comment] 2024-11-07 19:00
I ran into another issue after removing imunify360. I can setup a new machine based on cl7, but perhaps you can set it up yourself and test with cloudlinux, imunify360 and Plesk (since Plesk offers the entire bundle)?

**Comment by vizovitin** [comment] 2024-11-11 11:29
> I ran into another issue after removing imunify360.

There are no details, but that doesn't sound like a `cloudlinux7to8` issue. In this case, please go through the usual Plesk (or Imunify) support channels. If I'm mistaken, feel free to provide details here or file another issue.

**Comment by cloud86robb3rt** [comment] 2024-12-10 16:13
This issue is fixed in the new version v1.0.4.

**Closed** 2024-12-10 16:13 UTC
Labels: bug

**Comment by MrKoopie** [comment] 2024-12-10 17:33
I have justed test this and I can confirm the upgrade succeeds now. However, you do need to reinstall Imunify360. Not doing results in incorrect webserver configuration files.

**Comment by cloud86robb3rt** [comment] 2024-12-12 12:09
> I have justed test this and I can confirm the upgrade succeeds now. However, you do need to reinstall Imunify360. Not doing results in incorrect webserver configuration files.

This seems to be due missing dnf packages, we've fixed this by simple running an dnf install on 'imunify-ui-firewall-plesk' this installs all the dependencies for Plesk and fixes the /etc/httpd/conf.d/modsec2.imunify.conf config :).
